package aulajavaweb.model.enums;

public enum RacaGato {

	ABYSSINIAN, AMERICAN_BOBTAIL_LONGHAIR, AMERICAN_BOBTAIL_SHORTHAIR, AMERICAN_SHORTHAIR, 
	AMERICAN_WIREHAIR, ARABIAN_MAU, ASIAN_SEMI_LONG_HAIR, AUSTRALIAN_MIST, BENGAL, 
	BOBTAIL_JAPONÊS, BOMBAIM, BRAZILIAN_SHORTHAIR, BRITISH_LONGHAIR, BURMÊS, 
	CALIFORNIA_SPANGLED_CAT, CHAUSIE, CORNISH_REX, CURL_AMERICANO_PELO_CURTO, 
	CURL_AMERICANO_PELO_LONGO, CYMRIC, DEVON_REX, DOMESTIC_LONG_HAIRED, DOMESTIC_SHORT_HAIRED, 
	DON_SPHYNX, EGYPTIAN_MAU, EUROPEAN_EXOTIC_SHORTHAIR, GERMAN_REX, HAVANA, HIMALAIO, 
	KHAO_MANEE, KORAT, KURILIAN_BOBTAIL_LONGHAIR, KURILIAN_BOBTAIL_SHORTHAIR, LAPERM_LONGHAIR,
	LAPERM_SHORTHAIR, MAINE_COON, MANX, MEKONG_BOBTAIL, MUNCHKIN_LONGHAIR, MUNCHKIN_SHORTHAIR,
	NEBELUNG, NORWEGIAN_FOREST_CAT, OCICAT, OJOS_AZULES_SHORTHAIR, ORIENTAL_LONGHAIR, 
	ORIENTAL_SHORTHAIR, PERSA, PETERBALD, PIXIEBOB_LONGHAIR, PIXIEBOB_SHORTHAIR, 
	RAGAMUFFIN, RAGDOLL, RUSSO_AZUL, SAGRADO_DA_BIRMÂNIA, SAVANNAH_CAT, SCOTTIS_FOLD, 
	SELKIRK_REX_LONGHAIR, SELKIRK_REX_SHORTHAIR, SERENGETI, SIAMÊS, SIBERIAN, SINGAPURA, 
	SNOWSHOE, SOKOKE, SOMALI, SPHYNX, THAI, TONKINESE_SHORTHAIR, TOYGER, TURKISH_ANGORÁ, 
	TURKISH_VAN, YORK_CHOCOLATE
}
